name: 'my_project'
version: '1.0.0'
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"

vars:
  sample_size: 50
  sumup_charge: 0.0169
  stripe_charge: 0.015